# Generated by Django 4.2.16 on 2024-11-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cart',
            new_name='old_cart',
        ),
    ]
