# Generated by Django 4.2.16 on 2024-11-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAuthentication', '0002_rename_cart_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='old_cart',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
