# Generated by Django 4.2.16 on 2024-11-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAuthentication', '0003_alter_profile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='town',
            field=models.CharField(blank=True, choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Eldoret', 'Eldoret'), ('Thika', 'Thika'), ('Nyeri', 'Nyeri'), ('Machakos', 'Machakos'), ('Naivasha', 'Naivasha'), ('Meru', 'Meru'), ('Kakamega', 'Kakamega'), ('Embu', 'Embu'), ('Kericho', 'Kericho'), ('Malindi', 'Malindi'), ('Kitale', 'Kitale'), ('Garissa', 'Garissa'), ('Nanyuki', 'Nanyuki'), ('Isiolo', 'Isiolo'), ('Lamu', 'Lamu'), ('Wajir', 'Wajir'), ('Narok', 'Narok'), ('Kilifi', 'Kilifi'), ('Bungoma', 'Bungoma'), ('Voi', 'Voi'), ('Homa Bay', 'Homa Bay'), ('Marsabit', 'Marsabit'), ('Moyale', 'Moyale'), ('Mandera', 'Mandera'), ('Lodwar', 'Lodwar'), ('Bomet', 'Bomet'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Migori', 'Migori'), ('Makueni', 'Makueni'), ('Taveta', 'Taveta'), ('Nyahururu', 'Nyahururu'), ('Sotik', 'Sotik'), ('Kapenguria', 'Kapenguria')], max_length=100),
        ),
    ]
