# Generated by Django 4.2.16 on 2024-11-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAuthentication', '0004_profile_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
