# Generated by Django 4.2.16 on 2024-11-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt_number',
        ),
    ]
