# Generated by Django 4.2.16 on 2024-11-10 07:34
import uuid

from django.db import migrations


def populate_receipt_numbers(apps, schema_editor):
    Order = apps.get_model('order', 'Order')
    for order in Order.objects.filter(receipt_number__isnull=True):
        order.receipt_number = uuid.uuid4()
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_receipt_number'),
    ]

    operations = [
        migrations.RunPython(populate_receipt_numbers),

    ]
