# Generated by Django 4.2.16 on 2024-11-10 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20241110_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
