# Generated by Django 4.2.16 on 2025-02-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.CharField(choices=[('now', 'Pay now'), ('on_delivery', 'Pay upon delivery')], default='Pay now', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('paypal', 'Paypal'), ('credit/debit', 'Credit/debit card')], default='Mpesa', editable=False, max_length=20),
        ),
    ]
