# Generated by Django 4.2.16 on 2025-02-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_payment_date_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
